### ISSUE TITLE
unable to unmount /mnt/mnt\0/mnt\0

### ISSUE THREAD

**Issue by dazoe** [fitu996/overlayRoot.sh#2]
to get it to work i needed to change ```echo -n "\$xx\0"``` to ```echo -ne "\$xx\0"```
this was on a raspberry pi zero w using buildroot

**Comment by fitu996** [comment]
What's your default shell?

The "\$xx\0" shouldn't be interpreted by echo.

**Comment by dazoe** [comment]
Default shell was BusyBox's ash

**Comment by fitu996** [comment]
Sorry but I still don't know why this problem appeared. `echo -e` is not in posix standard so I need another solution.

**Comment by Robin-Sch** [comment]
I installed the script and added init=/sbin/overlayRoot.sh to grub and updated grub.

I get the error:
```
umount /mnt/sys/firmware/efi/efivars\0/mnt/sys\0/mnt/run\0/mnt/mnt\0/mnt\0: no mount point specified
[overlayRoot.sh] ERROR: could not umount old root
[overlayRoot.sh] there is something wrong with overlayRoot.sh. type exit and press enter to ignore and continue
```

Solution:
Reboot into recovery USB (pressing enter doesn't work because the file won't be saved to the disk).

Change `echo -n "\$xx\0"` to `echo -ne "\$xx\0"` (add an `e`).

OS: Arch Linux

**Comment by fitu996** [comment]
Fixed by https://github.com/fitu996/overlayRoot.sh/commit/a4e6398bb3c83a696d3d4676e3ac1c717a4a9537

Reopen the issue if there is not.
